project:
  type: website
  render:
    - "*qmd"
  output-dir: docs

website:
  sidebar:
    style: "docked"
    logo: "img/logo.png"
    search: true
    contents:
      - text: "Capstone Final Report"
        href: final_report.qmd
      - text: "Capstone Proposal"
        href: proposal.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



