name: ci

on: [push]

jobs:

  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install tectonic
        run: sudo snap refresh && sudo snap install tectonic

      - name: Test with pytest (skip integration tests)
        run: poetry run pytest --cov -m "not integration"

      - name: Test package building process
        run: poetry build

      - name: Get built wheel path
        run: |
          {
            echo 'WHEELFILE<<EOF'
            find ./dist/ -name '*.whl' -print
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Upload test build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: $WHEELFILE
          path: ./dist/$WHEELFILE